name: Full Spectrum Life
favicon: null
layout_spectrum: 0.25598
typography_spectrum: 0.49681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8a5265'
    - '#3b6338'
    - '#6b915a'
    - '#d3af90'
  brandStrength: 0.875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
