name: Full Spectrum Life
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.49681
title: Living a Full Spectrum Life - Randy Thomas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a601c7'
    - '#303afb'
    - '#007c40'
    - '#ff850a'
    - '#fcfd00'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
