name: Full Spectrum Life
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.49681
title: Living a Full Spectrum Life - Randy Thomas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#fbfbfb'
    - '#dfdfdf'
    - '#a9a9a9'
    - '#5d5d5d'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
