name: Full Spectrum Life
favicon: null
layout_spectrum: 0.25598
typography_spectrum: 0.9924943891819566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0b0d'
    - '#ffffff'
    - '#6b6d67'
    - '#bfa8c5'
    - '#d61f3f'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.813470421358943
  rhythmicContrast: 0.5988199678249657
purpose: []
